version: 0.2

phases:
  pre_build:
    commands:
      # Install AWS CLI
      - pip3 install --upgrade awscli
      # Authenticate Docker with ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)


  build:
    commands:
      # Build the Docker image
      - docker build -t $ECR_REPOSITORY_URI:latest ./app

  post_build:
    commands:
      # Push the Docker image to Amazon ECR
      - docker push $ECR_REPOSITORY_URI:latest

      # Update kubeconfig and deploy application to EKS cluster
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $CLUSTER_NAME
      - kubectl version
      - kubectl config view
      - kubectl get nodes
      - kubectl apply -f ./app/deployment.yaml -f ./app/service.yaml