version: 0.2

phases:
  pre_build:
    commands:
      # Install AWS CLI
      - pip3 install --upgrade awscli

      # Login to Amazon ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

  build:
    commands:
      # Build the Docker image
      - docker build -t $ECR_REPOSITORY_URI:latest ./app/.dockerfile

  post_build:
    commands:
      # Push the Docker image to Amazon ECR
      - docker push $ECR_REPOSITORY_URI:latest

    # Deploy application to EKS cluster
    - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $CLUSTER_NAME
    - kubectl apply -f ./app/deployment.yaml -f ./app/service.yaml
