version: 0.2

env:
  variables:
    ECR_REPOSITORY_URI: "default-value" # Default value, in case the variable is not provided by CodeBuild

phases:
  pre_build:
    commands:
      # Install AWS CLI
      - apt-get update && apt-get install -y python3-pip
      - pip3 install --upgrade awscli

      # Login to Amazon ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      # Build the Docker image
      - docker build -t $ECR_REPOSITORY_URI:latest ./app/.dockerfile

  post_build:
    commands:
      # Push the Docker image to Amazon ECR
      - docker push $ECR_REPOSITORY_URI:latest
