# Use the official Python image as base
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. crypto_service.proto

# Expose port 50051
EXPOSE 50051

# Update client configuration file with server IP address
RUN sed -i 's/SERVER_ADDRESS/tf-lb-2024042714334162000000000f-1707577661.us-east-1.elb.amazonaws.com/g' crypto_client.py

# Run the gRPC client
CMD ["python", "./app/crypto_server.py"]
