apiVersion: v1
kind: Service
metadata:
  name: simetrik-app-service
spec:
  selector:
    app: simetrik-app
  ports:
    - protocol: TCP  # Specify protocol as TCP for gRPC
      port: 80
      targetPort: 50051  # Adjusted target port for gRPC
  type: LoadBalancer
